### ISSUE TITLE
trouble shooting

### ISSUE THREAD

**Issue by minnjeong** [minnjeong/Todo-list-Challenge-2#2]
완료 버튼 클릭 시 오류 메시지

ERROR
props.completeRemoveHandler is not a function
TypeError: props.completeRemoveHandler is not a function
    at onClick (http://localhost:3000/static/js/bundle.js:262:28)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:11076:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:11120:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:11177:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:11191:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:15335:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:15361:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:15372:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:15381:7)
    at http://localhost:3000/static/js/bundle.js:15541:16
ERROR
props.completeRemoveHandler is not a function
TypeError: props.completeRemoveHandler is not a function
    at onClick (http://localhost:3000/static/js/bundle.js:262:28)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:11076:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:11120:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:11177:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:11191:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:15335:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:15361:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:15372:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:15381:7)
    at http://localhost:3000/static/js/bundle.js:15541:16

**Comment by minnjeong** [comment]
수정 완료 !
에러 원인 : props.completeRemoveHandler is not defined
해결 방법 : TodoItem.jsx 에서 <button className="complete-button" onClick={() => props.**completeHandler**(props.todo.id)}> 로 수정.... 사소한 실수..
